### ISSUE TITLE
Size of availability store

### ISSUE THREAD

**Issue by maethor** [shinken-monitoring/mod-mongo-logs#2]
@mohierf have you tested this module on your production environment? Do you have an idea about the size it takes?

EDIT: An other way to ask the question. What is the size of an availability entry? Then, the total size should match a simple equation.

I ask this question to know if it would be reasonable to store the availability for all services.

**Comment by mohierf** [comment]
I made a simple test in mongo shell: 

```
MongoDB shell version: 2.6.7
connecting to: test
> use shinkenn
switched to db shinkenn
> use shinken
switched to db shinken
> db.availability.stats()
{
        "ns" : "shinken.availability",
        "count" : 14165,
        "size" : 7025840,
        "avgObjSize" : 496,
        "storageSize" : 11182080,
        "numExtents" : 6,
        "nindexes" : 2,
        "lastExtentSize" : 8388608,
        "paddingFactor" : 1,
        "systemFlags" : 1,
        "userFlags" : 1,
        "totalIndexSize" : 1275456,
        "indexSizes" : {
                "_id_" : 466032,
                "availability" : 809424
        },
        "ok" : 1
}

> db.availability.totalSize()
12457536
```

Around 14k records for 12.5Mb. I would say that we may assume 1Kb / record ...

**Comment by maethor** [comment]
OK, so it's completely insignificant compared to perfdata.

**Comment by mohierf** [comment]
Yes ... this is why I was strongly interested in this approch : few data, real time statistics, no livestatus = happy sys admin :-)

**Comment by naparuba** [comment]
especially "no livestatus" ^^

**Comment by mohierf** [comment]
+1 for you @naparuba :-)
