### ISSUE TITLE
Error load module: cannot import name Connection

### ISSUE THREAD

**Issue by Azef1** [shinken-monitoring/mod-mongo-logs#6]
Hi,
In my arbiter load (debug mode), i have a error to load the module: 
![errmod](https://cloud.githubusercontent.com/assets/15362041/10973759/12b026d6-83df-11e5-8afc-2d07d3582720.PNG)

"cannot import name Connection" ??
help please

**Comment by mohierf** [comment]
It is related to your version of `pymongo` ... which version did you installed? `mongo-logs` requires version 3 ...

**Comment by Azef1** [comment]
I installed pymongo 3.0.3

python -c "import pymongo; print(pymongo.version); print(pymongo.has_c())"
Result: 3.0.3 False

python -c "import sys; print(sys.version)"
Result: 2.7.5

Version of module is  1.0.2b (mod-mongo-logs-1.0.2b.zip) 

MongoDB shell version: 3.0.4

**Comment by Azef1** [comment]
Now, it's works,
Soluce: I have reinstalled module "mod-mongo-logs" with version 1.0.2 (no beta).

**Comment by mohierf** [comment]
Fine. I did not have time to make more tests on this module ... sorry.
